src/communities/urls.py
from django.urls import path, include

from communities.views import societies, religions, social_groups

urlpatterns = [
    path('', include(([
        path('societies/creator/<uuid:slug>/',
             societies.index, name='society-index'),
        path('api/societies/', societies.society_collection,
             name='society-collection'),
        path('societies/view/<uuid:slug>/',
             societies.society_edit, name='society-edit'),
        path('api/societies/<uuid:slug>/update-type/', societies.update_type,
             name='society-update-type'),
        path('api/societies/<uuid:slug>/update-gov/', societies.update_gov,
             name='society-update-gov'),
        path('api/societies/<uuid:slug>/update-leadership/', societies.update_lead,
             name='society-update-leadership'),
        path('api/societies/<uuid:slug>/update-military/', societies.update_military,
             name='society-update-military'),
        path('api/societies/<uuid:slug>/update-social-capital/', societies.update_social_capital,
             name='society-update-social-capital'),
        path('api/societies/<uuid:slug>/update-hierarchy/', societies.update_hierarchy,
             name='society-update-hierarchy'),
        path('api/societies/<uuid:slug>/update-origin/', societies.update_origin,
             name='society-update-origin'),
        path('api/societies/<uuid:slug>/update-economy/', societies.update_economy,
             name='society-update-economy'),
        path('api/societies/<uuid:slug>/update-legal/', societies.update_legal,
             name='society-update-legal'),
        path('api/societies/<uuid:slug>/update-rivals/', societies.update_rivals,
             name='society-update-rivals'),
        path('api/societies/<uuid:slug>/update-extra/', societies.update_extra,
             name='society-update-extra'),

         path('religions/creator/<uuid:slug>/',
              religions.index, name='religion-index'),
         path('api/religions/', religions.religion_collection,
              name='religion-collection'),
         path('religions/view/<uuid:slug>/', religions.religion_edit,
              name='religion-edit'),
         path('api/religions/<uuid:slug>/update-deities/', religions.update_deities,
              name='religion-update-deities'),
         path('api/religions/<uuid:slug>/update-beliefs/', religions.update_beliefs,
              name='religion-update-beliefs'),
         path('api/religions/<uuid:slug>/update-practices/', religions.update_practices,
              name='religion-update-practices'),
         path('api/religions/<uuid:slug>/update-origins/', religions.update_origins,
              name='religion-update-origins'),
         path('api/religions/<uuid:slug>/update-organization/', religions.update_org,
              name='religion-update-org'),
         path('api/religions/<uuid:slug>/update-holy-objects/', religions.update_hobj,
              name='religion-update-hobj'),
         path('api/religions/<uuid:slug>/update-holidays/', religions.update_holidays,
              name='religion-update-holidays'),
         path('api/religions/<uuid:slug>/update-figures/', religions.update_rfigs,
              name='religion-update-figures'),
         path('api/religions/<uuid:slug>/update-extra/', religions.update_extra,
              name='religion-update-extra'),

         path('social_groups/creator/<uuid:slug>/',
              social_groups.index, name='social-group-index'),
         path('api/social_groups/', social_groups.sg_collection,
              name='social-group-collection'),
         path('social_groups/view/<uuid:slug>/', social_groups.sgroup_edit,
              name='sgroup-edit'),
         path('api/social_groups/<uuid:slug>/update-type/', social_groups.update_type,
              name='sgroup-update-type'),
         path('api/social_groups/<uuid:slug>/update-goals/', social_groups.update_goals,
              name='sgroup-update-goals'),
         path('api/religions/<uuid:slug>/update-structure/', social_groups.update_structure,
              name='sgroup-update-structure'),
         path('api/social_groups/<uuid:slug>/update-structure/', social_groups.update_structure,
              name='sgroup-update-structure'),
         path('api/social_groups/<uuid:slug>/update-cohesiveness/', social_groups.update_cohes,
              name='sgroup-update-cohes'),
         path('api/social_groups/<uuid:slug>/update-extra/', social_groups.update_extra,
              name='sgroup-update-extra'),
         ], 'communities'), namespace='communities'))
]

src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/litevolve/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('', include('projects.urls')),
    path('', include('universes.urls')),
    path('', include('stories.urls')),
    path('', include('communities.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/projects/urls.py
from django.urls import path, include

from projects.views import projects, tasks

urlpatterns = [
    path('', include(([
        path('projects/creator/<uuid:slug>/', projects.index, name='index'),
        path('projects/view/<uuid:slug>/',
             projects.edit, name='view'),
        path('api/projects/',
             projects.project_collection, name='project-collection'),
        path('api/projects/<uuid:slug>/',
             projects.project_single, name='project-single'),
        
        path('tasks/view/<uuid:slug>/',
             tasks.edit, name='task-view'),
        path('api/projects/<uuid:slug>/tasks/',
             tasks.task_collection, name='task-collection'),
        path('api/tasks/<uuid:slug>/content_type/', tasks.create_ctype, name="task-ctype"),
        path('api/tasks/<uuid:slug>/update-complete/', tasks.update_complete, name="task-complete")
    ], 'projects'), namespace='projects'))
]

src/stories/urls/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include(([
        path('stories/creator/<int:pk>/', views.author_stories, name='my-stories'),
        path('stories/create/', views.create_story, name="create"),
        path('stories/<int:pk>/view', views.story_details, name='view'),
        path('stories/<int:pk>/characters', views.story_characters, name='story-characters'),
        path('stories/<int:pk>/author-characters', views.author_characters, name='author-characters'),
        path('stories/<int:pk>/character-assignment/', views.assign_story_character, name='assign-story-character'),
        path('stories/<int:pk>/acts/', views.act_list, name='act-list'),
        path('stories/<int:pk>/act-create/', views.act_create, name='act-create'),
        path('acts/<int:pk>/', views.act_details, name='act-view'),
        path('act/<int:pk>/scene-create/', views.scene_create, name='scene-create'),
        path('scenes/<int:pk>/', views.scene_details, name='scene-view'),
        path('scenes/<int:pk>/characters/', views.scene_characters, name="scene-characters"),
        path('scenes/<int:pk>/character-assignment/', views.assign_scene_character, name='assign-scene-character'),
        path('scenes/<int:pk>/dialogue/', views.add_dialogue, name="scene-dialogue"),
    ], 'stories'), namespace='stories')),
]

src/templates/partials/group_menu.html
<div id="menu-group" class="mainmenu d-none">
    <a href="{% url 'communities:society-index' request.user.profile.slug %}" class="mainmenu__item">Societies</a>
    <a href="{% url 'communities:religion-index' request.user.profile.slug %}" class="mainmenu__item">Religions</a>
    <a href="{% url 'communities:social-group-index' request.user.profile.slug %}" class="mainmenu__item">Social Groups</a>
</div>

<!--$( "div.tumble" ).toggleClass( "bounce" )-->

src/templates/partials/menu.html
<nav class="menu">
    <div class="menu__item menu__item--1" data-direction="bt">
        <div class="menu__item-inner">
            {% include 'partials/universe_menu.html' %}
            {% include 'partials/group_menu.html' %}
            {% include 'partials/story_menu.html' %}
            <p class="label label--topleft label--vert-mirror">the important stuff</p>
            <p class="label label--bottomright label--vert">made in bannockburn</p>
        </div>
    </div>
    <div class="menu__item menu__item--2" data-direction="lr">
        <div class="menu__item-inner">
            <div class="menu__item-map"></div>
            <a href="#" class="menu__item-hoverlink">The location</a>
        </div>
    </div>
    <div class="menu__item menu__item--3" data-direction="bt">
        <div class="menu__item-inner">
            <div class="sidemenu">
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="uni-link">Universes</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="comm-link">Communities</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="char-link">Characters</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="struct-link">Constructions</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="story-link">Stories</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner" id="files-link">Files</span></a>
                <a href="#" class="sidemenu__item"><span class="sidemenu__item-inner">...</span></a>
            </div>
        </div>
    </div>
    <div class="menu__item menu__item--4" data-direction="rl">
        <div class="menu__item-inner">
            <p style="color:#c96d1c;" class="label label--topleft label--line">Projects</p>
            <a href="{% url 'projects:index' request.user.profile.slug %}" style="color: #024449; font-size: 8rem;" class="menu__item-link"><i class="icofont-tasks"></i></a>
        </div>
    </div>
    <div class="menu__item menu__item--5" data-direction="tb">
        <div class="menu__item-inner">
            <p class="quote">Hail to thee, our infantry, still brave, beyond the grave</p>
        </div>
    </div>
    <button style="color: #024449; font-size: 2rem;" class="action action--menu"><span class="icon icon--menu" id="icon-menu"><i class="icofont-compass-alt"></i></span></button>
    <button style="font-size: 2rem;" class="action action--close"><span class="icon icon--close" id="icon-close"><i class="icofont-close-line"></i></span></button>
</nav>

src/templates/partials/sidebar.html
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>LitEvolve</h3>
        <strong>LE</strong>
    </div>

    <ul class="list-unstyled components">
        <li>
            <a href="#uniSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="fas fa-atom"></i>
                Universe Builder
            </a>
            <ul class="collapse list-unstyled" id="uniSubmenu">
                <li>
                    <a href="{% url 'universes:index' request.user.profile.slug %}">Universes</a>
                </li>
                <li>
                    <a href="{% url 'universes:rule-index' request.user.profile.slug %}">Natrual Laws</a>
                </li>
                <li>
                    <a href="#">Particles</a>
                </li>
                <li>
                    <a href="#">Atoms</a>
                </li>
                <li>
                    <a href="#">Elements</a>
                </li>
                <li>
                    <a href="#">Compounds</a>
                </li>
                <li>
                    <a href="#">Celestial Body</a>
                </li>
                <li>
                    <a href="#">Natural Phenomena</a>
                </li>
                <li>
                    <a href="#">Seasons</a>
                </li>
                <li>
                    <a href="#">Places</a>
                </li>
                <li>
                    <a href="#">Natural Objects</a>
                </li>
                <li>
                    <a href="#">Species</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#"><i class="fas fa-user-astronaut"></i> Characters</a>
        </li>
        <li>
            <a href="#"><i class="fas fa-book"></i> Stories</a>
        </li>
        <li>
            <a href="#worldSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="fas fa-users"></i>
                Communities
            </a>
            <ul class="collapse list-unstyled" id="worldSubmenu">
                <li>
                    <a href="{% url 'communities:society-index' request.user.profile.slug %}">Societies</a>
                </li>
                <li>
                    <a href="{% url 'communities:religion-index' request.user.profile.slug %}">Religions</a>
                </li>
                <li>
                    <a href="{% url 'communities:social-group-index' request.user.profile.slug %}">Social Groups</a>
                </li>
            </ul>
        </li>
    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a class="download text-center" href="#">
                <i class="fas fa-power-off"></i>
                Logout
            </a>
        </li>
    </ul>
</nav>

src/templates/partials/story_menu.html
<div id="menu-story" class="mainmenu d-none">
    <a href="{% url 'stories:index' request.user.profile.slug %}" class="mainmenu__item">Stories</a>
</div>

<!--$( "div.tumble" ).toggleClass( "bounce" )-->

src/templates/partials/text-editor.html
<form method="POST" id="{{ form_id }}">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ field_selector }}">{{ label }}</label>
      <textarea class="description" name="{{ field_selector }}" id="{{ field_selector }}" rows="3">{{ data }}</textarea>
    </div>
    <button type="submit" class="btn btn-second">Save</button>
</form>

src/templates/partials/topbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-main mb-3">
  <a class="navbar-brand" href="#">
    <div class="avatar-block">
        {% for album in request.user.profile.albums.all  %}
            {% for photo in album.photos.all %}
                {% if photo.default and album.name == request.user.username %}
                    <img src="{{ MEDIA_URL }}{{photo.file}}" style="height:44px; width: 44px;" class="mx-auto img-thumbnail rounded-circle d-block avatar" alt="avatar">
                {% endif %}
            {% endfor %}
        {% endfor %}
    </div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.name }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
    </ul>
    <!-- Button trigger modal -->
    <button type="button" data-toggle="modal" data-target="#myModal" class="btn bg-second navbar-btn rounded-circle">
      <i class="icofont-search"></i>
    </button>
  </div>
</nav>

src/templates/partials/universe_menu.html
<div id="menu-universe" class="mainmenu">
    <a href="{% url 'universes:index' request.user.profile.slug %}" class="mainmenu__item">Universes</a>
    <a href="#" class="mainmenu__item">Fundamental Forces</a>
    <a href="#" class="mainmenu__item">Fields</a>
    <a href="{% url 'dimensions:index' request.user.profile.slug %}" class="mainmenu__item">Dimensions</a>
    <a href="{% url 'rules:index' request.user.profile.slug %}" class="mainmenu__item">Natural Laws</a>
    <a href="{% url 'particles:particle-index' request.user.profile.slug %}" class="mainmenu__item">Particles</a>
    <a href="{% url 'elements:index' request.user.profile.slug %}" class="mainmenu__item">Elements</a>
    <a href="{% url 'celestial_bodies:index' request.user.profile.slug %}" class="mainmenu__item">Celestial Bodies</a>
    <a href="{% url 'natural_phenomenon:index' request.user.profile.slug %}" class="mainmenu__item">Natural Phenomenon</a>
    <a href="{% url 'seasons:index' request.user.profile.slug %}" class="mainmenu__item">Seasons</a>
    <a href="{% url 'places:index' request.user.profile.slug %}" class="mainmenu__item">Places</a>
    <a href="{% url 'natural_objects:index' request.user.profile.slug %}" class="mainmenu__item">Natural Objects</a>
    <a href="{% url 'species:index' request.user.profile.slug %}" class="mainmenu__item">Species</a>
</div>