src/accounts/urls.py
from django.urls import include, path

from .views import accounts, profile

urlpatterns = [
    path('logout/', accounts.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', accounts.UserSignUpView.as_view(), name='user_signup'),
    path('accounts/signup/success/', accounts.signup_success, name='success'),
    path('workspace/', include(([
        path('<uuid:slug>/', profile.user_profile, name='index'),
    ], 'accounts'), namespace='profile')),
]

src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/litevolve/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('', include('projects.urls')),
    path('', include('universes.urls')),
    path('', include('stories.urls')),
    path('', include('communities.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/projects/urls.py
from django.urls import path, include

from projects.views import projects, tasks

urlpatterns = [
    path('', include(([
        path('projects/creator/<uuid:slug>/', projects.index, name='index'),
        path('projects/view/<uuid:slug>/',
             projects.edit, name='view'),
        path('api/projects/',
             projects.project_collection, name='project-collection'),
        path('api/projects/<uuid:slug>/',
             projects.project_single, name='project-single'),
        
        path('tasks/view/<uuid:slug>/',
             tasks.edit, name='task-view'),
        path('api/projects/<uuid:slug>/tasks/',
             tasks.task_collection, name='task-collection'),
        path('api/tasks/<uuid:slug>/content_type/', tasks.create_ctype, name="task-ctype"),
        path('api/tasks/<uuid:slug>/update-complete/', tasks.update_complete, name="task-complete")
    ], 'projects'), namespace='projects'))
]

src/projects/models.py
import uuid

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from accounts.models import UserProfile
from utils import obj, calc

# Create your models here.

class ProjectManager(models.Manager):
    def ctasks(self, creator, slug):
        return self.filter(slug=slug,tasks__is_complete=True, creator=creator)

    def ctasks_count(self, creator, slug):
        return self.filter(slug=slug, tasks__is_complete=True, creator=creator).exclude().count()

class Project(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    name = models.CharField(max_length=255, blank=True)
    day = models.DateField(blank=True)
    start = models.DateTimeField(**obj.NULL_AND_BLANK)
    end = models.DateTimeField(**obj.NULL_AND_BLANK)
    details = models.TextField(**obj.NULL_AND_BLANK)
    is_complete = models.BooleanField(default=False, blank=True)
    creator = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='projects', blank=True)

    objects = ProjectManager()

    def __str__(self):
       return self.name

    @property
    def progress(self):
        tasks = self.tasks.count()
        ctasks = Project.objects.ctasks_count(slug=self.slug, creator=self.creator)
        progress = calc.get_progress(goal=tasks, completed=ctasks)
        # print(tasks)
        # print(ctasks)
        return progress


class Task(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    name = models.CharField(max_length=255, blank=True)
    day = models.DateField(blank=True)
    start = models.DateTimeField(**obj.NULL_AND_BLANK)
    end = models.DateTimeField(**obj.NULL_AND_BLANK)
    details = models.TextField(**obj.NULL_AND_BLANK)
    is_complete = models.BooleanField(default=False, blank=True)
    #collaborators = models.ManyToManyField(UserProfile, related_name='tasks', blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks', blank=True)
    # Below the mandatory fields for generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, **obj.NULL_AND_BLANK)
    object_id = models.PositiveIntegerField(**obj.NULL_AND_BLANK)
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.name

src/projects/views/projects.py
import simplejson as json
from datetime import datetime, date
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from accounts.models import UserProfile
from projects.models import Project, Task
from projects.serializer import ProjectSerializer

def index(request, slug, template_name='projects/index.html', data={}):
    data['creator'] = UserProfile.objects.get(slug=slug, user=request.user)
    return render(request, template_name, data)

def edit(request, slug, template_name='projects/edit.html', data={}):
    try:
        project = Project.objects.get(slug=slug)
    except Project.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    data['project'] = project
    return render(request, template_name, data)


@api_view(['GET', 'POST'])
def project_collection(request):
    if request.method == 'GET':
        projects = Project.objects.filter(creator=request.user.profile)
        serializer = ProjectSerializer(projects, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        data = {
            'name': request.data.get('name'),
            'day': date.today(),
            'creator': request.user.profile.pk
        }
        serializer = ProjectSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'DELETE'])
def project_single(request, slug):
    try:
        project = Project.objects.get(slug=slug)
    except Project.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProjectSerializer(project)
        return Response(serializer.data)

    elif request.method == 'DELETE':
        project.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

src/projects/views/tasks.py
import json
from datetime import datetime, date
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from accounts.models import UserProfile
from projects.models import Project, Task
from projects.serializer import ProjectSerializer, TaskSerializer
from universes.models import (NaturalLaw,
                                CelestialBody,
                                NaturalPhenomena,
                                Season,
                                NaturalObject,
                                Species,
                                Place,
                                Particle,
                                Element,
                                Universe)
from utils import calc

def edit(request, slug, template_name='tasks/edit.html', data={}):
    data['task'] = Task.objects.get(slug=slug)
    return render(request, template_name, data)

@api_view(['GET', 'POST'])
def task_collection(request, slug):
    try:
        project = Project.objects.get(slug=slug)
    except Project.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        tasks = Task.objects.filter(project=project)
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)
        
    elif request.method == 'POST':
        data = {
            'name': request.data.get('name'),
            'day': date.today(),
            'project': project.pk,
            'creator': request.user.profile.pk
        }
        serializer = TaskSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            json_resp = {
                'data': serializer.data,
                'progress': project.progress
            }
            return JsonResponse(json_resp, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'DELETE'])
def task_single(request, slug):
    try:
        task = Task.objects.get(slug=slug)
    except Task.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TaskSerializer(task)
        return Response(serializer.data)

    elif request.method == 'DELETE':
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@api_view(['GET', 'POST'])
def create_ctype(request, slug):
    try:
        task = Task.objects.get(slug=slug)
    except Task.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'POST':
        if request.POST['ctype'] == 'Universe':
            ctype = Universe.objects.create(name=request.POST['name'], creator=request.user.profile)
        task.content_object = ctype
        task.save()
        data = {
            'slug': ctype.slug,
            'name': ctype.name,
            'url': ctype.url,
        }
        return JsonResponse(data)

@api_view(['GET', 'PATCH'])
def update_complete(request, slug):
    try:
        task = Task.objects.get(slug=slug)
    except Task.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TaskSerializer(task)
        return Response(serializer.data)

    if request.method == 'PATCH':
        data = {
            'is_complete': request.data.get('is_complete'),
        }
        serializer = TaskSerializer(task, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

src/projects/templates/tasks/edit.html
{% extends 'app.html' %}
{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'profile:index' request.user.profile.slug %}">Workspace</a></li>
    <li class="breadcrumb-item"><a href="{% url 'projects:index' request.user.profile.slug %}">Projects</a></li>
    <li class="breadcrumb-item"><a href="{% url 'projects:view' task.project.slug %}"><span id="slug_{{task.project.slug}}">{{ task.project.name }}</span></a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ task.name }}</li>
{% endblock breadcrumbs %}

{% block content %}
<div class="row">
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Overview</a>
            <a class="nav-link" id="v-pills-edit-tab" data-toggle="pill" href="#v-pills-edit" role="tab" aria-controls="v-pills-edit" aria-selected="true">Edit</a>
        </div>
    </div>
    <div class="col-9">
        <div id="results"></div>
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                
                <header class="row">
                    <div class="col">
                        <span class="card-title h2" id="tslug_{{task.slug}}">{{ task.name }}</span>
                    </div>
                </header>
                <hr />
                {% if task.content_object == None %}
                    <button type="button" id="ctype-btn" class="btn btn-primary" data-toggle="modal" data-target="#ctypeModal">
                        Add content type
                    </button>
                {% endif %}
                <div class="{% if task.content_object == None %}d-none{% endif %}" id="ctype-content">
                    <a href="{{ task.content_object.url }}">{{ task.content_object }}</a>
                </div>
                <form method="POST" id="complete-form">
                    {% csrf_token %}
                    <input type="hidden" name="complete" id="complete" value="1" />
                    <button id="ic-btn" type="submit" {% if task.is_complete == True %}disabled{% endif %} class="btn btn-primary">
                        {% if task.is_complete == False %}
                            Complete
                        {% else %}
                            Completed
                        {% endif %}
                    </button>
                </form>
            </div>
            <div class="tab-pane fade show" id="v-pills-edit" role="tabpanel" aria-labelledby="v-pills-edit-tab">
                <h2 class="card-title">Edit</h2>
            </div>
        </div>
    </div>
    {% include 'modals/create_ctype.html' %}
</div>

{% endblock content %}

{% block javascript %}
<script src="{% static 'js/projects.js' %}"></script>
{% endblock javascript %}